title: Practice
author: Securithid
email: securithid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Practice before creating SecHops site

# social links
twitter_username: @Securithid
github_username:  @Securithid

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
